package org.spongycastle.asn1.pkcs;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

public abstract interface PKCSObjectIdentifiers
{
  public static final ASN1ObjectIdentifier aeB;
  public static final ASN1ObjectIdentifier aeC;
  public static final ASN1ObjectIdentifier aeD;
  public static final ASN1ObjectIdentifier aeE;
  public static final ASN1ObjectIdentifier aeF;
  public static final ASN1ObjectIdentifier aeG;
  public static final ASN1ObjectIdentifier ahY;
  public static final ASN1ObjectIdentifier alj;
  public static final ASN1ObjectIdentifier all;
  public static final ASN1ObjectIdentifier apG;
  public static final ASN1ObjectIdentifier aqA;
  public static final ASN1ObjectIdentifier aqB;
  public static final ASN1ObjectIdentifier aqC;
  public static final ASN1ObjectIdentifier aqD;
  public static final ASN1ObjectIdentifier aqE;
  public static final ASN1ObjectIdentifier aqF;
  public static final ASN1ObjectIdentifier aqG;
  public static final ASN1ObjectIdentifier aqH;
  public static final ASN1ObjectIdentifier aqI;
  public static final ASN1ObjectIdentifier aqJ;
  public static final ASN1ObjectIdentifier aqK;
  public static final ASN1ObjectIdentifier aqL;
  public static final ASN1ObjectIdentifier aqM;
  public static final ASN1ObjectIdentifier aqN;
  public static final ASN1ObjectIdentifier aqO;
  public static final ASN1ObjectIdentifier aqP;
  public static final ASN1ObjectIdentifier aqQ;
  public static final ASN1ObjectIdentifier aqR;
  public static final ASN1ObjectIdentifier aqS;
  public static final ASN1ObjectIdentifier aqT;
  public static final ASN1ObjectIdentifier aqU;
  public static final ASN1ObjectIdentifier aqV;
  public static final ASN1ObjectIdentifier aqW;
  public static final ASN1ObjectIdentifier aqX;
  public static final ASN1ObjectIdentifier aqY;
  public static final ASN1ObjectIdentifier aqZ;
  public static final ASN1ObjectIdentifier aqp = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
  public static final ASN1ObjectIdentifier aqq = aqp.ﾆ("1");
  public static final ASN1ObjectIdentifier aqr = aqp.ﾆ("2");
  public static final ASN1ObjectIdentifier aqs;
  public static final ASN1ObjectIdentifier aqt;
  public static final ASN1ObjectIdentifier aqu;
  public static final ASN1ObjectIdentifier aqv;
  public static final ASN1ObjectIdentifier aqw;
  public static final ASN1ObjectIdentifier aqx;
  public static final ASN1ObjectIdentifier aqy;
  public static final ASN1ObjectIdentifier aqz;
  public static final ASN1ObjectIdentifier arA;
  public static final ASN1ObjectIdentifier arB;
  public static final ASN1ObjectIdentifier arC;
  public static final ASN1ObjectIdentifier arD;
  public static final ASN1ObjectIdentifier arE;
  public static final ASN1ObjectIdentifier arF;
  public static final ASN1ObjectIdentifier arG;
  public static final ASN1ObjectIdentifier arH;
  public static final ASN1ObjectIdentifier arI;
  public static final ASN1ObjectIdentifier arJ;
  public static final ASN1ObjectIdentifier arK;
  public static final ASN1ObjectIdentifier arL;
  public static final ASN1ObjectIdentifier arM;
  public static final ASN1ObjectIdentifier arN;
  public static final ASN1ObjectIdentifier arO;
  public static final ASN1ObjectIdentifier arP;
  public static final ASN1ObjectIdentifier arQ;
  public static final ASN1ObjectIdentifier arR;
  public static final ASN1ObjectIdentifier arS;
  public static final ASN1ObjectIdentifier arT;
  public static final ASN1ObjectIdentifier arU;
  public static final ASN1ObjectIdentifier arV;
  public static final ASN1ObjectIdentifier arW;
  public static final ASN1ObjectIdentifier arX;
  public static final ASN1ObjectIdentifier arY;
  public static final ASN1ObjectIdentifier arZ;
  public static final ASN1ObjectIdentifier ara;
  public static final ASN1ObjectIdentifier arb;
  public static final ASN1ObjectIdentifier arc;
  public static final ASN1ObjectIdentifier ard;
  public static final ASN1ObjectIdentifier are;
  public static final ASN1ObjectIdentifier arf;
  public static final ASN1ObjectIdentifier arg;
  public static final ASN1ObjectIdentifier arh;
  public static final ASN1ObjectIdentifier ari;
  public static final ASN1ObjectIdentifier arj;
  public static final ASN1ObjectIdentifier ark;
  public static final ASN1ObjectIdentifier arl;
  public static final ASN1ObjectIdentifier arm;
  public static final ASN1ObjectIdentifier arn;
  public static final ASN1ObjectIdentifier aro;
  public static final ASN1ObjectIdentifier arp;
  public static final ASN1ObjectIdentifier arq;
  public static final ASN1ObjectIdentifier arr;
  public static final ASN1ObjectIdentifier ars;
  public static final ASN1ObjectIdentifier art;
  public static final ASN1ObjectIdentifier aru;
  public static final ASN1ObjectIdentifier arv;
  public static final ASN1ObjectIdentifier arw;
  public static final ASN1ObjectIdentifier arx;
  public static final ASN1ObjectIdentifier ary;
  public static final ASN1ObjectIdentifier arz;
  public static final ASN1ObjectIdentifier asA = asy.ﾆ("2");
  public static final ASN1ObjectIdentifier asB = asy.ﾆ("3");
  public static final ASN1ObjectIdentifier asC = asy.ﾆ("4");
  public static final ASN1ObjectIdentifier asD = asy.ﾆ("5");
  public static final ASN1ObjectIdentifier asE = asy.ﾆ("6");
  public static final ASN1ObjectIdentifier asF = asy.ﾆ("6");
  public static final ASN1ObjectIdentifier asG = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
  public static final ASN1ObjectIdentifier asH = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
  public static final ASN1ObjectIdentifier asa;
  public static final ASN1ObjectIdentifier asb;
  public static final ASN1ObjectIdentifier asc;
  public static final ASN1ObjectIdentifier asd;
  public static final ASN1ObjectIdentifier ase;
  public static final ASN1ObjectIdentifier asf;
  public static final ASN1ObjectIdentifier asg;
  public static final ASN1ObjectIdentifier ash;
  public static final ASN1ObjectIdentifier asi;
  public static final ASN1ObjectIdentifier asj;
  public static final ASN1ObjectIdentifier ask;
  public static final ASN1ObjectIdentifier asl;
  public static final ASN1ObjectIdentifier asm;
  public static final ASN1ObjectIdentifier asn;
  public static final ASN1ObjectIdentifier aso;
  public static final ASN1ObjectIdentifier asp;
  public static final ASN1ObjectIdentifier asq;
  public static final ASN1ObjectIdentifier asr;
  public static final ASN1ObjectIdentifier ass;
  public static final ASN1ObjectIdentifier ast;
  public static final ASN1ObjectIdentifier asu;
  public static final ASN1ObjectIdentifier asv;
  public static final ASN1ObjectIdentifier asw;
  public static final ASN1ObjectIdentifier asx;
  public static final ASN1ObjectIdentifier asy;
  public static final ASN1ObjectIdentifier asz;
  
  static
  {
    apG = aqp.ﾆ("3");
    aqs = aqp.ﾆ("4");
    aqt = aqp.ﾆ("5");
    aqu = aqp.ﾆ("6");
    aqv = aqp.ﾆ("7");
    aqw = aqp.ﾆ("8");
    aqx = aqp.ﾆ("9");
    aqy = aqp.ﾆ("10");
    aqz = aqp.ﾆ("11");
    aqA = aqp.ﾆ("12");
    aqB = aqp.ﾆ("13");
    aqC = aqp.ﾆ("14");
    aqD = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
    aqE = aqD.ﾆ("1");
    aqF = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
    aqG = aqF.ﾆ("1");
    aqH = aqF.ﾆ("4");
    aqI = aqF.ﾆ("3");
    aqJ = aqF.ﾆ("6");
    aqK = aqF.ﾆ("10");
    aqL = aqF.ﾆ("11");
    aqM = aqF.ﾆ("13");
    aqN = aqF.ﾆ("12");
    all = new ASN1ObjectIdentifier("1.2.840.113549.3");
    aqO = all.ﾆ("7");
    aqP = all.ﾆ("2");
    aqQ = all.ﾆ("4");
    alj = new ASN1ObjectIdentifier("1.2.840.113549.2");
    aqR = alj.ﾆ("2");
    aqS = alj.ﾆ("4");
    aqT = alj.ﾆ("5");
    aqU = alj.ﾆ("7");
    aqV = alj.ﾆ("8");
    aqW = alj.ﾆ("9");
    aqX = alj.ﾆ("10");
    aqY = alj.ﾆ("11");
    aqZ = new ASN1ObjectIdentifier("1.2.840.113549.1.7");
    aeB = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1");
    aeC = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2");
    aeD = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3");
    aeE = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4");
    aeF = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5");
    aeG = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6");
    ara = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
    arb = ara.ﾆ("1");
    arc = ara.ﾆ("2");
    ard = ara.ﾆ("3");
    are = ara.ﾆ("4");
    arf = ara.ﾆ("5");
    arg = ara.ﾆ("6");
    arh = ara.ﾆ("7");
    ari = ara.ﾆ("8");
    arj = ara.ﾆ("9");
    ark = ara.ﾆ("13");
    arl = ara.ﾆ("14");
    arm = ara.ﾆ("15");
    ahY = ara.ﾆ("16");
    arn = ara.ﾆ("20");
    aro = ara.ﾆ("21");
    arp = ara.ﾆ("22.1");
    arq = ara.ﾆ("22");
    arr = arq.ﾆ("1");
    ars = arq.ﾆ("2");
    art = ara.ﾆ("23");
    aru = art.ﾆ("1");
    arv = ara.ﾆ("15.1");
    arw = ara.ﾆ("15.2");
    arx = ara.ﾆ("15.3");
    ary = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
    arz = ary.ﾆ("2");
    arA = ary.ﾆ("4");
    arB = ary.ﾆ("9");
    arC = ary.ﾆ("23");
    arD = ary.ﾆ("31");
    arE = ahY.ﾆ("3");
    arF = arE.ﾆ("9");
    arG = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
    arH = arG.ﾆ("1");
    arI = arG.ﾆ("2");
    arJ = arG.ﾆ("3");
    arK = arG.ﾆ("4");
    arL = arG.ﾆ("5");
    arM = arG.ﾆ("6");
    arN = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
    arO = arN.ﾆ("1");
    arP = arN.ﾆ("4");
    arQ = arN.ﾆ("5");
    arR = arN.ﾆ("10");
    arS = arN.ﾆ("11");
    arT = arN.ﾆ("12");
    arU = arN.ﾆ("47");
    arV = arN.ﾆ("7");
    arW = arN.ﾆ("14");
    arX = arN.ﾆ("15");
    arY = arN.ﾆ("16");
    arZ = arN.ﾆ("17");
    asa = arN.ﾆ("18");
    asb = arN.ﾆ("19");
    asc = arN.ﾆ("20");
    asd = arN.ﾆ("21");
    ase = arN.ﾆ("22");
    asf = arN.ﾆ("23");
    asg = arN.ﾆ("24");
    ash = arN.ﾆ("25");
    asi = arN.ﾆ("26");
    asj = arN.ﾆ("27");
    ask = arX;
    asl = arY;
    asm = arZ;
    asn = asb;
    aso = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
    asp = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
    asq = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
    asr = asq.ﾆ("10.1");
    ass = asr.ﾆ("1");
    ast = asr.ﾆ("2");
    asu = asr.ﾆ("3");
    asv = asr.ﾆ("4");
    asw = asr.ﾆ("5");
    asx = asr.ﾆ("6");
    asy = asq.ﾆ("1");
    asz = asy.ﾆ("1");
  }
}


/* Location:           C:\Users\Dan\Documents\android\periscope\classes-dex2jar.jar
 * Qualified Name:     org.spongycastle.asn1.pkcs.PKCSObjectIdentifiers
 * JD-Core Version:    0.7.0.1
 */